[package]
name = "starcoin-move-explain"
version = "1.0.0-alpha.1"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
structopt = "0.3.21"
stdlib = { package="stdlib", path = "../stdlib"}
diem-workspace-hack = { git = "https://github.com/starcoinorg/diem", rev="35b83099823d040a310a52f96622ab5e97aed0f5" }
errmapgen = { git = "https://github.com/starcoinorg/diem", rev="35b83099823d040a310a52f96622ab5e97aed0f5" }
move-core-types = { git = "https://github.com/starcoinorg/diem", rev = "35b83099823d040a310a52f96622ab5e97aed0f5" }
bcs-ext = { package="bcs-ext", path = "../../commons/bcs_ext" }

[features]
default = []
