[package]
name = "starcoin-move-explain"
version = "1.0.0-alpha.1"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
structopt = "0.3.21"
stdlib = { package="stdlib", path = "../stdlib"}
errmapgen = { git = "https://github.com/starcoinorg/diem", rev="a318bb619320e8f3c8ec7e3e3bbbe1af8bc52dee" }
move-core-types = { git = "https://github.com/starcoinorg/diem", rev = "a318bb619320e8f3c8ec7e3e3bbbe1af8bc52dee" }
bcs-ext = { package="bcs-ext", path = "../../commons/bcs_ext" }

[features]
default = []
